sudo: false
language: python
python:
- '3.7'
install:
- pip install --upgrade tox
script: tox
deploy:
  provider: pypi
  user: marcolivierbouch
  password:
    secure: KEwY0M4oE65IJN+sDiLYVdU23PHO7zO3tMd/l2taNDYVZGP+XvUWzMEis6+DgtAIR06UOJ6rm+pGRykiM74HaKtxmfitsf7bSVO1Dh9YIc3/InxQSWAX0zokvUvIV45PsL5XLQQcyosIQo/9mu52gz9F4AY60Z4YMi0ndAaQEmsZyeObA77TjQgazNTaWZ4clAUYaebejigK+/W9n23x528y3bozekvP7ZSpVtiUS9m88uY5bW5DoOucf41vFvZvYkwRZeNtW4ztEckM2Y9SXuLlnXNQu3FhyBFbYLrdpy5uKXvNIr1P0xjOUJjkVnmwccYyPfs4/uv4ZwQwO/lFD9qB+XrLsMFiagBnE8jq7ePEChXJVAiQtTfSgFJwg2usboUITEaq/rFnh25R3kLCftrm50287kOybaMNRuQIDHorfQiZkjoaPsCLH85LWl4HmEhGXiwI75kwdx4qcVcAaa1AHu79O0TLJcK+W0oVK+FJQgg0+ZmIDRqR+8pdDo5M4lcScubFIVywtOil+UL4XJ1ubl8nJf3pONgi/xU9cB9sKG6uIjo7xDjr7pOAV84M6J11UHUbr6lhNQHfU3CDKSFFeExmFg0tQYmivrXrdNC+gXBQ0fcBM4SkpAmM9OFZ1X66lBYpoNMvVItVJ4vNDmI6tI9RXf923wUy20LGTlM=
  on:
    branch: master
